### ISSUE TITLE
Some artifacts  are missing

### ISSUE THREAD

**Issue by hicto** [robolectric/robolectric-samples#13]
Hi @erd,
when I run the samples, some errors occurs:
 http://stackoverflow.com/questions/30475268/unable-to-resolve-artifact-missing-using-android-studiogradle-and-robolectri  

Could you give some suggestions?

**Comment by erd** [comment]
Have you tried running "gradle --refresh-dependencies"? Also, you don't
need to specify "shadows-core" and "android-all" in your build.gradle.
Robolectric will pick the right versions at runtime.

**Comment by hicto** [comment]
Thanks @erd , I try to running `gradle --refresh-dependencies` first, but the errors are still there. Then I remote the `caches` directory under $GRADLE_HOME and try running `gradle build` but fails again. The errors are all the same.

**Comment by erd** [comment]
I haven't been able to reproduce this.
